# this workflow is triggered by an API call when there is a new PyPI release of LiteLLM
name: Build and Publish Docker Image
on:
  push:
    branches:
      - models-sort
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag version you want to build"
        type: string
        default: "latest"
      commit_hash:
        description: "Commit hash"
        required: true

jobs:
  docker-hub-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit_hash }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/litellm:${{ github.event.inputs.tag || 'latest' }}
          platforms: linux/amd64,linux/arm64

