# this workflow allows building and pushing the database image from any branch/commit
name: Build, Publish LiteLLM Database Docker Image
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch or ref to build from (e.g., main, tag-routing, or a commit hash)"
        type: string
        required: true
        default: "main"
      tag:
        description: "The tag version you want to build"
        type: string
        required: true
      release_type:
        description: "The release type you want to build. Can be 'latest', 'stable', 'dev', 'rc'"
        type: string
        default: "latest"

# Build and push database image only
jobs:
  # print branch, commit hash, tag, and release type
  print:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Branch/Ref: ${{ github.event.inputs.branch }}"
          echo "Tag: ${{ github.event.inputs.tag }}"
          echo "Release type: ${{ github.event.inputs.release_type }}"

  build-and-push-image-database:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Log in to Docker Hub
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-database
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/litellm-database
      # Configure multi platform Docker builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@e0e4588fad221d38ee467c0bffd91115366dc0c5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@edfb0fe6204400c56fbfd3feba3fe9ad1adfa345

      - name: Build and push Database Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: ./docker/Dockerfile.database
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/litellm-database:${{ github.event.inputs.tag || 'latest' }}
          labels: ${{ steps.meta-database.outputs.labels }}
          platforms: linux/amd64,linux/arm64
